# see https://docs.docker.com/compose/compose-file/

version: "3"
services:
    web:
        build: ./web
        ports:
            - "5000:8000"
        command: ./entrypoint.sh
        volumes:
            - ./web:/web
        stdin_open: true
        tty: true
